version: "3"
services:
  docker_go:
    container_name: "docker_go"
    build: "./"
    ports:
      - 9001:9001
    volumes:
      - ./example/project1:/go/src/exampleProject1
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      APP_ENV: dev
